#!/bin/sh
set -e
touch source.tar.gz
cd "$(dirname "$0")/../.."
tar -cvz \
    --exclude-vcs \
    --exclude-vcs-ignores \
    --exclude=source.tar.gz \
    --exclude=.github \
    --exclude=docs \
    --exclude=bindings \
    --exclude=examples \
    --exclude=test \
    --exclude=script \
    --exclude=scripts \
    --exclude=corpus \
    --exclude=tools \
    --exclude=assets \
    --exclude=tags \
    --exclude=zig-cache \
    --exclude=zig-out \
    --exclude=tree-sitter/test \
    --exclude=tree-sitter/cli \
    --exclude=tree-sitter/highlight \
    --exclude=tree-sitter-java/bindings \
    --exclude=tree-sitter-java/script \
    --exclude=tree-sitter-java/test \
    --exclude=tree-sitter-rpmspec/queries/rpmspec \
    --exclude=treez/build.zig \
    --exclude=treez/build.zig.zon \
    -f tree-sitter/source.tar.gz \
    tree-sitter